defaults:
  - override /model: base
  - override /dataset: base

evaluate:
  subset: test
  model_name: classifier_model_v1
  model_metadata_file_path: /home/Jang/workspace/models/classifier_model_v1.yaml
  mlflow:
    exp_name: Evaluate Animals10 classifier
    exp_desc: Evaluate a classifier model
    exp_tags:
      dataset: Animals10
