deploy:
  model_name: classifier_model_v1
  model_metadata_file_name: classifier_model_v1.yaml
  prefect:
    work_root: ~/workspace/deploy/evidently_workspaces
    deployment_name: drift_detection_evidently
