defaults:
  - override /model: base
  - override /dataset: base
  
overrides:
    train:
      num_workers: 2
      hparams:
        epochs: 4
        batch_size: 128
        init_lr: 0.001
      mlflow:
        exp_name: Train classifier model
        exp_desc: Train a classifier model
        exp_tags:
          dataset: Animals10
